config/routes.rb
Rottenpotatoes::Application.routes.draw do
  resources :movies do
    resources :reviews, only: [:new, :create, :index]
  end

  # Authentication Routes
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # map '/' to be a redirect to '/movies'
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ActiveRecord::Base  
  has_many :reviews, dependent: :destroy

  def self.all_ratings
    %w[G PG PG-13 R]
  end

  def self.with_ratings(ratings, sort_by)
    if ratings.nil?
      all.order sort_by
    else
      where(rating: ratings.map(&:upcase)).order sort_by
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user

  validates :rating, presence: true, inclusion: { in: 1..5 }
  validates :comments, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews, dependent: :destroy  # เชื่อมกับ reviews และลบรีวิวเมื่อผู้ใช้ถูกลบ

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :force_index_redirect, only: [:index]

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @all_ratings = Movie.all_ratings
    @movies = Movie.with_ratings(ratings_list, sort_by)
    @ratings_to_show_hash = ratings_hash
    @sort_by = sort_by
    # remember the correct settings for next time
    session['ratings'] = ratings_list
    session['sort_by'] = @sort_by
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  private

  def force_index_redirect
    return unless !params.key?(:ratings) || !params.key?(:sort_by)

    flash.keep
    url = movies_path(sort_by: sort_by, ratings: ratings_hash)
    redirect_to url
  end

  def ratings_list
    params[:ratings]&.keys || session[:ratings] || Movie.all_ratings
  end

  def ratings_hash
    ratings_list.to_h { |item| [item, "1"] }
  end

  def sort_by
    params[:sort_by] || session[:sort_by] || 'id'
  end

  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def new
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to movie_path(@movie), notice: "Review added successfully!"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.find(params[:id])

    if @review.user == current_user # เช็คว่าเป็นเจ้าของรีวิวหรือไม่
      @review.destroy
      redirect_to movie_path(@movie), notice: "Review deleted successfully."
    else
      redirect_to movie_path(@movie), alert: "You can only delete your own reviews."
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comments)
  end

  def require_login
    unless current_user
      redirect_to login_path, alert: "You must be logged in to write a review."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.email}!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome, #{@user.email}!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ? "odd" : "even"
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
<head>
  <title>Rotten Potatoes!</title>
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  
  <!-- Bootstrap Icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
  
  <%= stylesheet_link_tag 'application', 'media' => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg bg-primary text-white mb-3">
      <div class="container">
        <h1 class="title">Rotten Potatoes!</h1>

        <%# ลิงก์ล็อกอิน / ล็อกเอาต์ / สมัครสมาชิก %>
        <div class="ml-auto">
          <% if logged_in? %>
            <span class="mr-2">Welcome, <%= current_user.email %>!</span>
            <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-light" %>
          <% else %>
            <%= link_to "Login", login_path, class: "btn btn-light mr-2" %>
            <%= link_to "Sign Up", signup_path, class: "btn btn-light mr-2" %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/movies/edit.html.erb
<h2>Edit Existing Movie</h2>
<%= form_tag movie_path(@movie), :method => :put do %>
  <%= label :movie, :title, 'Title', class: 'col-form-label' %>
  <%= text_field :movie, 'title', class: 'form-control' %>
  <%= label :movie, :rating, 'Rating', class: 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R'], {}, {class: 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', class: 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, class: 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Update Movie Info', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, class: 'btn btn-secondary' %>
<% end %>

app/views/movies/index.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<h2>All Movies</h2>

<%#  Part 2: Start here... %>

<%= form_tag movies_path, method: :get, id: 'ratings_form' do %>
  <%= hidden_field_tag 'sort_by', @sort_by %>
  Include:
  <% @all_ratings.each do |rating| %>
    <div class="form-check  form-check-inline">
      <%= label_tag "ratings[#{rating}]", rating, class: 'form-check-label' %>
      <%= check_box_tag "ratings[#{rating}]", '1', (@ratings_to_show_hash.include?(rating)),
        class: 'form-check-input' %>
    </div>
  <% end %>
  <%= submit_tag 'Refresh', id: 'ratings_submit', class: 'btn btn-primary' %>
<% end %>

<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th>
        <%= link_to 'Movie Title', movies_path({sort_by: 'title', ratings: @ratings_to_show_hash}),
                      id: 'title_header', class: ('bg-warning hilite' if @sort_by == 'title') %>
      </th>
      <th>Rating</th>
      <th>
        <%= link_to 'Release Date',
              movies_path({sort_by: 'release_date', ratings: @ratings_to_show_hash}),
              id: 'release_date_header', class: ('bg-warning hilite' if @sort_by == 'release_date') %>
      </th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= movie.title %>
        </td>
        <td>
          <%= movie.rating %>
        </td>
        <td>
          <%= movie.release_date %>
        </td>
        <td>
          <%= link_to "More about #{movie.title}", movie_path(movie) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add new movie', new_movie_path, class: 'btn btn-primary' %>

app/views/movies/new.html.erb
<h2>Create New Movie</h2>

<%= form_tag movies_path, class: 'form' do %>
  <%= label :movie, :title, 'Title', class: 'col-form-label' %>
  <%= text_field :movie, :title, class: 'form-control' %>
  <%= label :movie, :rating, 'Rating', class: 'col-form-label' %>
  <%= select :movie, :rating, ['G','PG','PG-13','R'], {}, {class: 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', class: 'col-form-label' %>
  <%= date_select :movie, :release_date, {}, class: 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Save Changes', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, class: 'btn btn-secondary' %>
<% end %>

app/views/movies/show.html.erb
<!-- app/views/movies/show.html.erb -->
<h2>Details about <em><%= @movie.title %></em></h2>

<ul id="details">
  <li>
    Rating:
    <%= @movie.rating %>
  </li>
  <li>
    Released on:
    <%= @movie.release_date.strftime("%B %d, %Y") %>
  </li>
</ul>

<h3>Description:</h3>
<p id="description">
  <%= @movie.description %>
</p>

<h3>Reviews:</h3>

<% if @movie.reviews.any? %>
  <div class="list-group">
    <% @movie.reviews.each do |review| %>
      <div class="list-group-item">
        <h5 class="mb-1">
          <strong><%= review.user.email %></strong>
        </h5>
        <p class="mb-1"><%= review.comments %></p>
        <small class="text-warning">
          <%= raw ("<i class='bi bi-star-fill'></i> " * review.rating) %>
        </small>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No reviews yet.</p>
<% end %>

<% if logged_in? %>
  <%= link_to "Write a Review", new_movie_review_path(@movie), class: "btn btn-success mt-3" %>
<% end %>

<div class="row mt-3">
  <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-primary col-2' %>
  <%= link_to 'Delete', movie_path(@movie), 'data-method': 'delete', 'data-confirm': 'Are you sure?', class: 'btn btn-danger col-2' %>
  <%= link_to 'Back to movie list', movies_path, class: 'btn btn-primary col-2' %>
</div>

app/views/reviews/_form.html.erb
<h2>Write a Review for <%= @movie.title %></h2>

<%= form_for([@movie, @movie.reviews.build]) do |f| %>
  <p>
    <%= f.label :rating, "Rating (1-5 stars):" %>
    <%= f.select :rating, options_for_select(1..5) %>
  </p>
  <p>
    <%= f.label :comments, "Comments:" %>
    <%= f.text_area :comments %>
  </p>
  <p>
    <%= f.submit "Submit Review", class: "btn btn-primary" %>
  </p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Write a Review for <%= @movie.title %></h1>

<%= form_for([@movie, @review]) do |f| %>
  <p>
    <%= f.label :rating, "Rating (1-5 stars):" %><br>
    <%= f.select :rating, options_for_select(1..5) %>
  </p>
  <p>
    <%= f.label :comments, "Comments:" %><br>
    <%= f.text_area :comments %>
  </p>
  <p>
    <%= f.submit "Submit Review", class: "btn btn-success" %>
  </p>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit "Sign Up" %>
  </p>
<% end %>